samples:
     *gz :  *gz
\nsample_groups:
- Biliary-AdenoCA
- Bladder-TCC
- Bone-Benign
- Bone-Epith
- Bone-Osteosarc
- Breast-AdenoCA
- Breast-DCIS
- Breast-LobularCA
- Cervix-AdenoCA
- Cervix-SCC
- CNS-GBM
- CNS-Medullo
- CNS-Oligo
- CNS-PiloAstro
- ColoRect-AdenoCA
- Eso-AdenoCA
- Head-SCC
- Kidney-ChRCC
- Kidney-RCC.clearcell
- Kidney-RCC.papillary
- Liver-HCC
- Lung-AdenoCA
- Lung-SCC
- Lymph-BNHL
- Lymph-CLL
- Myeloid-AML
- Myeloid-MPN
- Ovary-AdenoCA
- Panc-AdenoCA
- Panc-Endocrine
- Prost-AdenoCA
- Skin-Melanoma.acral
- Skin-Melanoma.cutaneous
- Skin-Melanoma.mucosal
- SoftTissue-Leiomyo
- SoftTissue-Liposarc
- Stomach-AdenoCA
- Thy-AdenoCA
- Uterus-AdenoCA
\nfeature_types:
-    signatures
-    nucleotidesubstitution1
-    nucleotidesubstitution3

grouped_samples:
    Biliary-AdenoCA : 
    Bladder-TCC : 
    Bone-Benign : 
    Bone-Epith : 
    Bone-Osteosarc : 
    Breast-AdenoCA : 
    Breast-DCIS : 
    Breast-LobularCA : 
    Cervix-AdenoCA : 
    Cervix-SCC : 
    CNS-GBM : 
    CNS-Medullo : 
    CNS-Oligo : 
    CNS-PiloAstro : 
    ColoRect-AdenoCA : 
    Eso-AdenoCA : 
    Head-SCC : 
    Kidney-ChRCC : 
    Kidney-RCC.clearcell : 
    Kidney-RCC.papillary : 
    Liver-HCC : 
    Lung-AdenoCA : 
    Lung-SCC : 
    Lymph-BNHL : 
    Lymph-CLL : 
    Myeloid-AML : 
    Myeloid-MPN : 
    Ovary-AdenoCA : 
    Panc-AdenoCA : 
    Panc-Endocrine : 
    Prost-AdenoCA : 
    Skin-Melanoma.acral : 
    Skin-Melanoma.cutaneous : 
    Skin-Melanoma.mucosal : 
    SoftTissue-Leiomyo : 
    SoftTissue-Liposarc : 
    Stomach-AdenoCA : 
    Thy-AdenoCA : 
    Uterus-AdenoCA : \n\nsimulation_n:
- 10
- 20
- 50
- 100
- 200

simulation_nlambda:
- 30
- 100
- 300

simulation_d:
- 3
- 7

beta_gamma_shape:
- 0
- 0.02
- 0.1
- 1
- 2.5

\nsimulation_n_generationC:
- 10
- 20
- 50
- 100

beta_gamma_shape_generationC:
- 0
- 0.0001
- 0.0002
- 0.0005
- 0.00075
<<<<<<< HEAD
<<<<<<< HEAD
- 0.001
- 0.002
=======
>>>>>>> 0e79d9d627c98691d22abede410a2d9e060b8d0b
=======
- 0.001
- 0.002
>>>>>>> b7516544d6581da5bf0a960e309788c1fba6dff6
- 0.005
- 0.001
- 0.002
- 0.01
- 0.02
- 0.05
- 0.1
- 0.2
- 0.4
- 0.6
- 0.8
- 2
- 4

simulation_d_generationC:
- 3
- 4
- 5
- 6
- 7

simulation_nlambda_generationC:
- 100

simulation_lambda_generationC:
- 10
- 80

\nsimulation_n_generationD:
- 20
- 25
- 30
- 35
- 40
- 45

beta_gamma_shape_generationD:
- 0
- 1

simulation_d_generationD:
- 3
- 7

simulation_nlambda_generationD:
- 100

simulation_lambda_generationD:
- 10
- 80

\nsimulation_n_generationE:
- 10
- 20
- 40
- 80

beta_gamma_shape_generationE:
- 0
- 1
- 2

simulation_d_generationE:
- 4
- 6
- 10

simulation_nlambda_generationE:
- 200

simulation_lambda_generationE:
- NA

\nsimulation_n_generationF:
- 20
- 50
- 100

beta_gamma_shape_generationF:
- 0
- 0.01
- 0.05
- 0.1
- 0.2
- 0.4
- 0.6
- 0.8
- 2
- 4

simulation_d_generationF:
- 3
- 4
- 5
- 6
- 7

simulation_nlambda_generationF:
- 100

simulation_lambda_generationF:
- 10
- 30
- 50
- 80

\nsimulation_n_generationG:
- 20
- 30
- 50
- 100

beta_gamma_shape_generationG:
- 0
- 0.01
- 0.1
- 0.6
- 4

simulation_d_generationG:
- 3
- 4
- 5
- 6

simulation_nlambda_generationG:
- 100

simulation_lambda_generationG:
- 80

\nsimulation_n_generationMixture1:
- 30
- 50
- 100

beta_gamma_shape_generationMixture1:
- 0
- 0.1
- 0.3

simulation_d_generationMixture1:
- 3
- 4
- 5

simulation_nlambda_generationMixture1:
- 100

simulation_lambda_generationMixture1:
- 0

\nsimulation_n_GenerationJnormBTwoLambdasOneChangingBeta:
- 20
- 30
- 50
- 100

beta_gamma_shape_GenerationJnormBTwoLambdasOneChangingBeta:
- 0
- 0.01
- 0.1
- 0.2
- 0.3
- 0.6
- 4

simulation_d_GenerationJnormBTwoLambdasOneChangingBeta:
- 3
- 4
- 5
- 6

simulation_nlambda_GenerationJnormBTwoLambdasOneChangingBeta:
- 100

simulation_lambda_GenerationJnormBTwoLambdasOneChangingBeta:
- 80

\nsimulation_n_GenerationMixturePCAWG:
- 50
- 100
- 200

beta_gamma_shape_GenerationMixturePCAWG:
- -12
- -10
- -8
- -4
- -2

simulation_d_GenerationMixturePCAWG:
- 7

simulation_nlambda_GenerationMixturePCAWG:
- 200

simulation_lambda_GenerationMixturePCAWG:
- 80

\nsimulation_n_GenerationMixturefewersignaturesPCAWG:
- 50
- 100
- 200

beta_gamma_shape_GenerationMixturefewersignaturesPCAWG:
- -999
- -12
- -10
- -8
- -4
- -2

simulation_d_GenerationMixturefewersignaturesPCAWG:
- 4

simulation_nlambda_GenerationMixturefewersignaturesPCAWG:
- 200

simulation_lambda_GenerationMixturefewersignaturesPCAWG:
- 80

\nsimulation_n_GenerationMixturefewersignaturespairedstomachPCAWG:
- 50
- 100
- 200

beta_gamma_shape_GenerationMixturefewersignaturespairedstomachPCAWG:
- -999
- -12
- -10
- -8
- -4
- -2
- -1
- 0
- 4
- 8
- 12

simulation_d_GenerationMixturefewersignaturespairedstomachPCAWG:
- 4

simulation_nlambda_GenerationMixturefewersignaturespairedstomachPCAWG:
- 200

simulation_lambda_GenerationMixturefewersignaturespairedstomachPCAWG:
- 80

\nsimulation_n_generationMixture1:
- 30
- 50
- 100

beta_gamma_shape_generationMixture1:
- 0
- 0.1
- 0.3

simulation_d_generationMixture1:
- 3
- 4
- 5

simulation_nlambda_generationMixture1:
- 100

simulation_lambda_generationMixture1:
- 0

